### ISSUE TITLE
DataStore<Preferences>

### ISSUE THREAD

**Issue by nynganini** [googlecodelabs/android-datastore#56] opened 2022-04-19 09:58 UTC
When creating UserPreferencesRepository the type should be DataStore\<Preferences\> instead of DataStore\<UserPreferences\>

**Comment by coodin** [comment] 2022-05-14 09:14
I have encounter the same problem so I decided to look the finished repository to check how they have done that and they have also written DataStore<Preferences> inside UserPreferencesRepository which is same with your answer.

**Comment by ccornici** [comment] 2022-07-31 09:59
Looks like they just write code in notepad and commit it, and never correct it either.

**Comment by donnfelker** [comment] 2022-09-08 18:06
These kind of mistakes can (and do) throw beginners off the wagon really easily. This should be fixed ASAP. 

Offending page: https://developer.android.com/codelabs/android-preferences-datastore#5

**Comment by mmoczkowski** [comment] 2022-09-09 15:43
Thanks, I agree this needs to be fixed asap. Working on it.

**Comment by mmoczkowski** [comment] 2022-09-09 15:49
Closing as a duplicate of #45

**Closed by mmoczkowski** 2022-09-09 15:49 UTC
