### ISSUE TITLE
Use "androidx.datastore:datastore" instead of datastore-core

### ISSUE THREAD

**Issue by Farbklex** [googlecodelabs/android-datastore#44] opened 2021-11-10 14:45 UTC
On page 5, the codelab instructs you to add the following dependencies:

```Groovy
dependencies {
    implementation  "androidx.datastore:datastore-core:1.0.0"
    implementation  "com.google.protobuf:protobuf-javalite:3.18.0"
    ...
}
```

On page 7, the codelab instructs to create a `DataStore` by using the `by dataStore` delegate:
```Kotlin
private val Context.userPreferencesStore: DataStore<UserPreferences> by dataStore(
...
```

`by dataStore` is part of a different library. `androidx.datastore:datastore:1.0.0`. The instructions on page 5 need to be updated to import `datastore` instead of `datastore-core`.

The `proto_datastore` branch already includes the [correct dependency](https://github.com/googlecodelabs/android-datastore/blob/proto_datastore/app/build.gradle#L71).

**Comment by purushottamyadavbattula** [comment] 2022-03-20 09:17
Faced this issue, please add this resolution to documentation

**Comment by mmoczkowski** [comment] 2022-09-09 20:23
Duplicate of #27

**Closed by mmoczkowski** 2022-09-09 20:23 UTC
