### ISSUE TITLE
variable "dataStore" should be "userPreferencesStore"

### ISSUE THREAD

**Issue by p26432** [googlecodelabs/android-datastore#47] opened 2021-11-17 03:30 UTC
The example code creates the variable "userPreferencesStore" but then references it as "dataStore" in the rest of the code.

**Comment by mmoczkowski** [comment] 2022-09-09 15:42
Thanks @p26432, this is noted, fix is under way. Closing as a duplicate of #45

**Closed by mmoczkowski** 2022-09-09 15:42 UTC
