### ISSUE TITLE
wrong constructor parameter name

### ISSUE THREAD

**Issue by yogaboyCZ** [googlecodelabs/android-datastore#58] opened 2022-09-04 07:45 UTC
in material U use 
class UserPreferencesRepository(
    private val userPreferencesStore: DataStore<UserPreferences>,

and in other snipets U use name for dataStore name dataStore not userPreferencesStore

UserPreferencesRepository(private val dataStore: DataStore<Preferences>) 

please fix it

**Comment by mmoczkowski** [comment] 2022-09-09 15:32
Thanks @yogaboyCZ. This is noted. A fix will be published soon. Closing since this is a duplicate of #47

**Comment by mmoczkowski** [comment] 2022-09-09 15:50
Sorry, not a duplicate. Reopening

**Comment by mmoczkowski** [comment] 2022-10-03 14:52
The constructor argument's name has been updated. https://developer.android.com/codelabs/android-preferences-datastore#5

Thanks again for reporting

**Closed by mmoczkowski** 2022-10-03 14:52 UTC
