### ISSUE TITLE
Incorrect parameter in the constructor of the UserPreferencesRepository 

### ISSUE THREAD

**Issue by Arunm619** [googlecodelabs/android-datastore#45] opened 2021-11-10 18:00 UTC
On [Page 6](https://developer.android.com/codelabs/android-preferences-datastore#5) of the lab, 

the third code snippet shows 
``` class UserPreferencesRepository(private val dataStore: DataStore<UserPreferences>)  ``` which is incorrect.

The right one is 

```class UserPreferencesRepository(private val dataStore: DataStore<Preferences>) ```

**Comment by mmoczkowski** [comment] 2022-09-09 15:49
Thank you. Fix will be issued soon.

**Comment by mmoczkowski** [comment] 2022-09-09 18:05
Duplicate of #30

**Comment by mmoczkowski** [comment] 2022-10-03 14:56
Thank you, this has been fixed

**Closed by mmoczkowski** 2022-10-03 14:56 UTC
